-- Phase 0 / Batch 0.1 / Chunk 0.1.1
-- Create medallion and control schemas in each environment.

USE ROLE ACCOUNTADMIN;

-- DEV
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_DEV.BRONZE;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_DEV.SILVER;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_DEV.GOLD;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_DEV.FEATURES;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_DEV.ML;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_DEV.OBSERVABILITY;

-- TEST
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_TEST.RAW;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_TEST.BRONZE;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_TEST.SILVER;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_TEST.GOLD;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_TEST.FEATURES;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_TEST.ML;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_TEST.OBSERVABILITY;

-- PROD
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_PROD.RAW;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_PROD.BRONZE;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_PROD.SILVER;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_PROD.GOLD;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_PROD.FEATURES;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_PROD.ML;
CREATE SCHEMA IF NOT EXISTS <ORG_PREFIX>_PROD.OBSERVABILITY;
