-- Phase 0 / Batch 0.1 / Chunk 0.1.3 baseline
-- Assign least-privilege roles to service users.

USE ROLE SECURITYADMIN;

GRANT ROLE <ORG_PREFIX>_AIRBYTE_ROLE TO USER <ORG_PREFIX>_AIRBYTE_SVC;
GRANT ROLE <ORG_PREFIX>_AIRFLOW_ROLE TO USER <ORG_PREFIX>_AIRFLOW_SVC;
GRANT ROLE <ORG_PREFIX>_DBT_ROLE TO USER <ORG_PREFIX>_DBT_SVC;

-- Default role and warehouse mappings
ALTER USER <ORG_PREFIX>_AIRBYTE_SVC SET DEFAULT_ROLE = <ORG_PREFIX>_AIRBYTE_ROLE;
ALTER USER <ORG_PREFIX>_AIRBYTE_SVC SET DEFAULT_WAREHOUSE = <ORG_PREFIX>_DEV_XS_WH;

ALTER USER <ORG_PREFIX>_AIRFLOW_SVC SET DEFAULT_ROLE = <ORG_PREFIX>_AIRFLOW_ROLE;
ALTER USER <ORG_PREFIX>_AIRFLOW_SVC SET DEFAULT_WAREHOUSE = <ORG_PREFIX>_DEV_XS_WH;

ALTER USER <ORG_PREFIX>_DBT_SVC SET DEFAULT_ROLE = <ORG_PREFIX>_DBT_ROLE;
ALTER USER <ORG_PREFIX>_DBT_SVC SET DEFAULT_WAREHOUSE = <ORG_PREFIX>_DEV_XS_WH;
