-- Phase 0 / Batch 0.1 validation script
-- Verifies role hierarchy and key grants for service principals.

SHOW ROLES LIKE '<ORG_PREFIX>_%';

-- Service role bindings
SHOW GRANTS TO USER <ORG_PREFIX>_AIRBYTE_SVC;
SHOW GRANTS TO USER <ORG_PREFIX>_AIRFLOW_SVC;
SHOW GRANTS TO USER <ORG_PREFIX>_DBT_SVC;

-- Environment role grants
SHOW GRANTS TO ROLE <ORG_PREFIX>_DEV_RW;
SHOW GRANTS TO ROLE <ORG_PREFIX>_TEST_RW;
SHOW GRANTS TO ROLE <ORG_PREFIX>_PROD_RW;

-- Warehouse usage grants
SHOW GRANTS ON WAREHOUSE <ORG_PREFIX>_DEV_XS_WH;
SHOW GRANTS ON WAREHOUSE <ORG_PREFIX>_TEST_SM_WH;
SHOW GRANTS ON WAREHOUSE <ORG_PREFIX>_PROD_MD_WH;
