-- Phase 0 / Batch 0.1 / Chunk 0.1.1
-- Create workload-specific warehouses and bind monitors.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS <ORG_PREFIX>_DEV_XS_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = <ORG_PREFIX>_DEV_MONITOR;

CREATE WAREHOUSE IF NOT EXISTS <ORG_PREFIX>_TEST_SM_WH
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = <ORG_PREFIX>_TEST_MONITOR;

CREATE WAREHOUSE IF NOT EXISTS <ORG_PREFIX>_PROD_MD_WH
  WITH WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = <ORG_PREFIX>_PROD_MONITOR;
