-- Phase 0 / Batch 0.1 / Chunk 0.1.1
-- Create environment-isolated databases.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS <ORG_PREFIX>_DEV;
CREATE DATABASE IF NOT EXISTS <ORG_PREFIX>_TEST;
CREATE DATABASE IF NOT EXISTS <ORG_PREFIX>_PROD;
