-- Phase 0 / Batch 0.1 / Chunk 0.1.1
-- Define role hierarchy for platform and workload isolation.

USE ROLE SECURITYADMIN;

-- Environment admin roles
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_DEV_ADMIN;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_TEST_ADMIN;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_PROD_ADMIN;

-- Functional service roles
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_AIRBYTE_ROLE;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_AIRFLOW_ROLE;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_DBT_ROLE;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_SNOWPARK_ML_ROLE;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_BI_READ_ROLE;

-- Reader/writer split by environment
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_DEV_RW;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_TEST_RW;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_PROD_RW;

CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_DEV_RO;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_TEST_RO;
CREATE ROLE IF NOT EXISTS <ORG_PREFIX>_PROD_RO;

-- Role hierarchy: service roles inherit least privilege env roles
GRANT ROLE <ORG_PREFIX>_DEV_RW TO ROLE <ORG_PREFIX>_AIRBYTE_ROLE;
GRANT ROLE <ORG_PREFIX>_DEV_RW TO ROLE <ORG_PREFIX>_AIRFLOW_ROLE;
GRANT ROLE <ORG_PREFIX>_DEV_RW TO ROLE <ORG_PREFIX>_DBT_ROLE;
GRANT ROLE <ORG_PREFIX>_DEV_RW TO ROLE <ORG_PREFIX>_SNOWPARK_ML_ROLE;
GRANT ROLE <ORG_PREFIX>_DEV_RO TO ROLE <ORG_PREFIX>_BI_READ_ROLE;

GRANT ROLE <ORG_PREFIX>_TEST_RW TO ROLE <ORG_PREFIX>_AIRFLOW_ROLE;
GRANT ROLE <ORG_PREFIX>_TEST_RW TO ROLE <ORG_PREFIX>_DBT_ROLE;
GRANT ROLE <ORG_PREFIX>_TEST_RW TO ROLE <ORG_PREFIX>_SNOWPARK_ML_ROLE;
GRANT ROLE <ORG_PREFIX>_TEST_RO TO ROLE <ORG_PREFIX>_BI_READ_ROLE;

GRANT ROLE <ORG_PREFIX>_PROD_RW TO ROLE <ORG_PREFIX>_AIRFLOW_ROLE;
GRANT ROLE <ORG_PREFIX>_PROD_RW TO ROLE <ORG_PREFIX>_DBT_ROLE;
GRANT ROLE <ORG_PREFIX>_PROD_RW TO ROLE <ORG_PREFIX>_SNOWPARK_ML_ROLE;
GRANT ROLE <ORG_PREFIX>_PROD_RO TO ROLE <ORG_PREFIX>_BI_READ_ROLE;
