-- Phase 0 / Batch 0.1 / Chunk 0.1.1
-- Grant database, schema, and warehouse privileges to environment roles.

USE ROLE SECURITYADMIN;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE <ORG_PREFIX>_DEV_XS_WH TO ROLE <ORG_PREFIX>_DEV_RW;
GRANT USAGE ON WAREHOUSE <ORG_PREFIX>_DEV_XS_WH TO ROLE <ORG_PREFIX>_DEV_RO;

GRANT USAGE ON WAREHOUSE <ORG_PREFIX>_TEST_SM_WH TO ROLE <ORG_PREFIX>_TEST_RW;
GRANT USAGE ON WAREHOUSE <ORG_PREFIX>_TEST_SM_WH TO ROLE <ORG_PREFIX>_TEST_RO;

GRANT USAGE ON WAREHOUSE <ORG_PREFIX>_PROD_MD_WH TO ROLE <ORG_PREFIX>_PROD_RW;
GRANT USAGE ON WAREHOUSE <ORG_PREFIX>_PROD_MD_WH TO ROLE <ORG_PREFIX>_PROD_RO;

-- DEV grants
GRANT USAGE ON DATABASE <ORG_PREFIX>_DEV TO ROLE <ORG_PREFIX>_DEV_RW;
GRANT USAGE ON DATABASE <ORG_PREFIX>_DEV TO ROLE <ORG_PREFIX>_DEV_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <ORG_PREFIX>_DEV TO ROLE <ORG_PREFIX>_DEV_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <ORG_PREFIX>_DEV TO ROLE <ORG_PREFIX>_DEV_RO;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE <ORG_PREFIX>_DEV TO ROLE <ORG_PREFIX>_DEV_RW;
GRANT SELECT ON ALL TABLES IN DATABASE <ORG_PREFIX>_DEV TO ROLE <ORG_PREFIX>_DEV_RO;
GRANT SELECT, USAGE ON ALL VIEWS IN DATABASE <ORG_PREFIX>_DEV TO ROLE <ORG_PREFIX>_DEV_RO;

-- TEST grants
GRANT USAGE ON DATABASE <ORG_PREFIX>_TEST TO ROLE <ORG_PREFIX>_TEST_RW;
GRANT USAGE ON DATABASE <ORG_PREFIX>_TEST TO ROLE <ORG_PREFIX>_TEST_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <ORG_PREFIX>_TEST TO ROLE <ORG_PREFIX>_TEST_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <ORG_PREFIX>_TEST TO ROLE <ORG_PREFIX>_TEST_RO;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE <ORG_PREFIX>_TEST TO ROLE <ORG_PREFIX>_TEST_RW;
GRANT SELECT ON ALL TABLES IN DATABASE <ORG_PREFIX>_TEST TO ROLE <ORG_PREFIX>_TEST_RO;
GRANT SELECT, USAGE ON ALL VIEWS IN DATABASE <ORG_PREFIX>_TEST TO ROLE <ORG_PREFIX>_TEST_RO;

-- PROD grants
GRANT USAGE ON DATABASE <ORG_PREFIX>_PROD TO ROLE <ORG_PREFIX>_PROD_RW;
GRANT USAGE ON DATABASE <ORG_PREFIX>_PROD TO ROLE <ORG_PREFIX>_PROD_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <ORG_PREFIX>_PROD TO ROLE <ORG_PREFIX>_PROD_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <ORG_PREFIX>_PROD TO ROLE <ORG_PREFIX>_PROD_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE <ORG_PREFIX>_PROD TO ROLE <ORG_PREFIX>_PROD_RW;
GRANT SELECT ON ALL TABLES IN DATABASE <ORG_PREFIX>_PROD TO ROLE <ORG_PREFIX>_PROD_RO;
GRANT SELECT, USAGE ON ALL VIEWS IN DATABASE <ORG_PREFIX>_PROD TO ROLE <ORG_PREFIX>_PROD_RO;
